# Generated by Django 4.2.1 on 2023-05-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ussd_booking.route')),
            ],
        ),
    ]
