# Generated by Django 4.2.1 on 2023-05-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_booking', '0002_route_price_alter_route_distance_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ussd_booking.bus'),
        ),
    ]
