# Generated by Django 4.2.1 on 2023-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_booking', '0003_trip_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
