# Generated by Django 4.2.1 on 2023-05-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_booking', '0005_remove_booking_timestamp_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
