# Generated by Django 4.2.1 on 2023-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_booking', '0006_booking_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(default=25567789865, max_length=20),
            preserve_default=False,
        ),
    ]
