# Generated by Django 4.2 on 2023-06-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_booking', '0008_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
