# Generated by Django 4.2.1 on 2023-07-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_booking', '0011_booking_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
    ]
